"""Human-readable evidence table, generated from the same numbers as metrics.json."""
from __future__ import annotations


def _signed(v):
    return "n/a" if v is None else f"{v:+}"


def headline_value(key: str, k: dict) -> str:
    v = k.get("value")
    if v is None:
        return f"withheld - {k.get('reason')}"
    if key.startswith("kpi_1") or key.startswith("kpi_2"):
        return f"**{v} min**"
    if key.startswith("kpi_3"):
        s = k["supporting"]
        return (f"**{v}%** of wait is before the driver arrives (median {s['median_request_to_on_scene_min']} min to arrive "
                f"vs {s['median_on_scene_to_pickup_min']} min at the curb); lower bound - see note")
    if key.startswith("kpi_4"):
        w, b = v["worst_5"][0], v["best_5"][0]
        return (f"P90 **{v['best_zone_p90_min']} - {v['worst_zone_p90_min']} min** across {v['zones_ranked']} ranked zones "
                f"(worst: {w['pickup_zone']}, {w['pickup_borough']}; best: {b['pickup_zone']}, {b['pickup_borough']}); "
                f"{v['zones_with_p90_over_1_5x_citywide']} zones exceed 1.5x the citywide P90")
    if key.startswith("kpi_5"):
        return (f"**{v['citywide_rate_per_100k']} per 100k rides** citywide "
                f"({v['citywide_passenger_complaints']:,} complaints / {v['citywide_hvfhv_pickups']:,} rides)")
    return str(v)


def evidence_markdown(month: str, mode: str, kpis: dict, support: dict, validation: list[dict], decisions: dict,
                      stats: dict, gate: dict, weather_meta: dict, friction_mapping: dict | None) -> str:
    L = []
    L.append(f"# Evidence table - NYC ride operations, {month}" + (" (SAMPLE RUN)" if mode == "sample" else "") + "\n")
    if mode == "sample":
        L.append("> **SAMPLE MODE - NOT THE COMPLETE DATASET.** These numbers come from the deterministic 10,000-ride sample "
                 "in `data/sample/`, which exercises every pipeline stage offline. Rates and zone rankings are not "
                 "representative, and zone thresholds are lowered for the sample. The real results are in `output/<month>/`.\n")
    L.append("_Generated by `run_pipeline.py`. Every number is also in `metrics.json`, with its full definition._\n")
    L.append(f"**Publish decision:** {'PUBLISHED' if gate['publish'] else 'BLOCKED'} · "
             f"311 friction KPI {'published' if gate['publish_friction_kpi'] else 'WITHHELD'} · "
             f"weather analysis {'published' if gate['publish_weather_analysis'] else 'WITHHELD'} · "
             f"checks {gate['status_counts']}\n")

    L.append("## Final KPIs\n")
    L.append("| # | Metric | Value | Definition | Population | Validation | Interpretation |")
    L.append("|---|---|---|---|---|---|---|")
    for i, (key, k) in enumerate(kpis.items(), 1):
        d = k["definition"]
        pop = f"{k['population_rides']:,} rides" if k.get("population_rides") is not None else "-"
        if key.startswith("kpi_3") and k.get("value") is not None:
            pop += f" ({k['population_share_of_kpi_population_pct']}% of KPI population)"
        L.append(f"| {i} | {d['name']} | {headline_value(key, k)} | `{d['formula']}` | {pop} | "
                 f"{k['validation_status']} | {d['interpretation']} |")

    k4 = kpis["kpi_4_p90_request_to_pickup_by_zone"]["value"]
    L.append("\n### KPI 4 detail - pickup zones by P90 (ranked zones only)\n")
    L.append("| Zone | Borough | Rides | Median | P90 |")
    L.append("|---|---|---|---|---|")
    for r in k4["worst_5"] + [None] + k4["best_5"]:
        L.append("| ... | | | | |" if r is None else
                 f"| {r['pickup_zone']} | {r['pickup_borough']} | {r['rides_in_kpi_population']:,} | "
                 f"{r['median_request_to_pickup_min']} | {r['p90_request_to_pickup_min']} |")
    L.append("\nAll zones (with 311 counts per zone): `zone_breakdown.csv`.\n")

    k5 = kpis["kpi_5_passenger_311_complaints_per_100k_rides"]
    if k5.get("value"):
        L.append("### KPI 5 detail - borough grain, read next to pickup reliability\n")
        L.append("| Borough | Passenger complaints | HVFHV pickups | Rate per 100k | P90 request-to-pickup |")
        L.append("|---|---|---|---|---|")
        for b, r in k5["value"]["by_borough"].items():
            L.append(f"| {b} | {r['passenger_complaints']} | {r['hvfhv_pickups']:,} | {r['rate_per_100k']} | {r['p90_request_to_pickup_min']} |")
        v5 = k5["value"]
        L.append("\n**Reading this table.** `HVFHV pickups` and `Rate per 100k` use **all zone-attributable pickups** "
                 "(flagged rides included); `P90 request-to-pickup` is computed on the **KPI population** "
                 "(in_zone_population), a slightly smaller set. Different denominators, on purpose: the rate needs every "
                 "ride a complaint could refer to, the P90 needs rides with a defensible wait.")
        if v5.get("passenger_complaints_unmapped"):
            L.append(f"\n**Numerator undercount.** {v5['passenger_complaints_unmapped']} passenger/company complaints "
                     "could not be mapped to a zone and are therefore absent from the numerator, so the published rate "
                     f"understates the true one by about {v5['rate_understatement_pct']}% (if unmapped complaints "
                     "resemble mapped ones). They are counted, never assigned by guess.")
        if friction_mapping:
            L.append(f"\n311 complaints mapped to a zone: {friction_mapping['mapped']:,}; no coordinates: "
                     f"{friction_mapping['no_coordinates']}; outside all zones: {friction_mapping['outside_all_zones']}; "
                     f"passenger/company complaints mapped: {friction_mapping.get('passenger_mapped')}/"
                     f"{friction_mapping.get('passenger_total')}. "
                     "311 records are contextual customer-friction signals at borough/zone-month grain, **not** ride-level interactions.\n")

    L.append("## Supporting analyses (not KPIs)\n")
    L.append("**By company** - " + "; ".join(f"{v['company']} ({c}): median {v['median']} / P90 {v['p90']} min "
                                             f"({v['rides']:,} rides)" for c, v in support["by_company"].items()))
    pa_ = support["precipitation_association"]
    if not pa_.get("withheld"):
        bb, hm = pa_["by_band"], pa_["hour_matched_median_diff_vs_dry_min"]
        L.append(f"\n**Precipitation** - median dry {bb['dry']['median']} / light {bb['light_rain']['median']} / "
                 f"moderate+ {bb['moderate_or_heavy_rain']['median']} min; hour-matched vs dry: light "
                 f"{_signed(hm['light_rain'])}, moderate+ {_signed(hm['moderate_or_heavy_rain'])} min. {pa_['conclusion']}")
    else:
        L.append(f"\n**Precipitation** - withheld: {pa_['reason']}")
    s = support["sensitivity_scheduled_rides"]
    a, e = s["kpi_population"], s["excluding_whole_minute_requests"]
    L.append(f"\n**Scheduled-ride sensitivity** - median {a['median']} -> {e['median']} min, P90 {a['p90']} -> {e['p90']} min "
             f"when whole-minute requests are excluded ({a['rides'] - e['rides']:,} rides). {s['note']}")
    if "nyc311_composition" in support:
        c = support["nyc311_composition"]
        L.append(f"\n**311 composition** - {c['complaints_by_category']}; pickup-reliability reasons: "
                 f"{c['pickup_reliability_reasons']}. {c['note']}")
    L.append("")

    L.append("## Validation gate\n")
    L.append("| Check | Status | Scope | Detail |")
    L.append("|---|---|---|---|")
    for r in validation:
        L.append(f"| `{r['check']}` | {r['status']} | {r['scope']} | {r['detail']} |")

    os_ = decisions["on_scene"]
    L.append("\n## Known / Unknown / Assumption / Limitation\n")
    L.append("**Known**")
    L.append(f"- {stats['rows']:,} completed HVFHV rides; {stats['kpi_population']:,} pass the lifecycle rules (KPI population).")
    L.append(f"- on_scene_datetime is populated for {os_['populated_share']:.2%} of rides but independently observed and "
             f"ordered for {os_['independently_observed_share']:.2%}.")
    L.append("- Rides with pickup before request exist; they are flagged, not deleted.")
    if friction_mapping:
        L.append(f"- {friction_mapping['mapped']:,} FHV complaints to 311 map to a taxi zone; most FHV complaints come "
                 "from non-passengers (street safety).")
    L.append("\n**Unknown**")
    L.append("- Which rides were pre-scheduled (no flag): request_datetime may be a booked slot for some rides.")
    L.append("- Unserved or cancelled requests: only completed trips are published.")
    L.append("- Which ride a 311 complaint refers to: 311 has no ride ID and is never linked to rides.")
    L.append("- Proprietary interventions (dispatch rules, incentives, surge): not observable in public data.")
    L.append("\n**Assumptions**")
    L.append("- HVFHV timestamps are NYC local time; weather is joined on the request hour (America/New_York).")
    L.append(f"- One weather grid cell ({weather_meta.get('grid_lat')}, {weather_meta.get('grid_lon')}) represents the whole city.")
    L.append("- 311 state-plane coordinates and the TLC zone shapefile share EPSG:2263 (verified by borough agreement).")
    L.append("- ride_id = row ordinal in the checksummed raw file; thresholds are in validation_report.json -> thresholds.")
    L.append("\n**Limitations**")
    L.append("- Request-to-pickup time is the rider-experienced interval, not driver wait time.")
    L.append("- KPI 3 is a lower bound: rides whose on_scene equals pickup to the second (no curb wait, so a 100% "
             "driver-arrival share) are not in its population.")
    L.append("- KPI 5 is a lower bound too: passenger complaints that did not map to a zone are absent from its numerator.")
    L.append("- Completed trips only (survivorship). Zone, borough and weather results are associations, not causes.")
    L.append("- 311 is sparse, covers all FHV types and reflects the propensity to complain, hence borough grain.")
    L.append("- No intervention data: the effect of operational actions cannot be evaluated.")
    return "\n".join(L) + "\n"
